[tool.poetry]
name = "protobufx"
version = "0.1.0"
description = ""
authors = ["tantaka <tomokazu.tantaka@glpgs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
grpcio-tools = "^1.54.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
