// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/addressbook.proto

package io.hexaforce.proto;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pb.Person people = 1;</code>
   */
  java.util.List<io.hexaforce.proto.Person> 
      getPeopleList();
  /**
   * <code>repeated .pb.Person people = 1;</code>
   */
  io.hexaforce.proto.Person getPeople(int index);
  /**
   * <code>repeated .pb.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .pb.Person people = 1;</code>
   */
  java.util.List<? extends io.hexaforce.proto.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .pb.Person people = 1;</code>
   */
  io.hexaforce.proto.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
