// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/addressbook.proto

package io.hexaforce.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .pb.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<io.hexaforce.proto.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .pb.Person.PhoneNumber phones = 4;</code>
   */
  io.hexaforce.proto.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .pb.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .pb.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends io.hexaforce.proto.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .pb.Person.PhoneNumber phones = 4;</code>
   */
  io.hexaforce.proto.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
