# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12&\n\x06phones\x18\x04 \x03(\x0b\x32\x16.pb.Person.PhoneNumber\x12\x30\n\x0clast_updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x41\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.pb.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\")\n\x0b\x41\x64\x64ressBook\x12\x1a\n\x06people\x18\x01 \x03(\x0b\x32\n.pb.Person25\n\x07Greeter\x12*\n\tSayPerson\x12\n.pb.Person\x1a\x0f.pb.AddressBook\"\x00\x42\x45\n\x12io.hexaforce.protoB\x11\x41\x64\x64ressBookProtosP\x01Z\x1agithub.com/hexaforce/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addressbook_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.hexaforce.protoB\021AddressBookProtosP\001Z\032github.com/hexaforce/proto'
  _PERSON._serialized_start=59
  _PERSON._serialized_end=310
  _PERSON_PHONENUMBER._serialized_start=200
  _PERSON_PHONENUMBER._serialized_end=265
  _PERSON_PHONETYPE._serialized_start=267
  _PERSON_PHONETYPE._serialized_end=310
  _ADDRESSBOOK._serialized_start=312
  _ADDRESSBOOK._serialized_end=353
  _GREETER._serialized_start=355
  _GREETER._serialized_end=408
# @@protoc_insertion_point(module_scope)
